image: Visual Studio 2017
shallow_clone: true
build: off
test: off
skip_branch_with_pr: true
skip_tags: true
configuration: Release

#branches:
#  only:
#  - master

only_commits:
  files:
  - appveyor.yml
  - src\*
  - nuspecs\*

nuget:
  disable_publish_on_pr: true

before_build:
  - nuget restore PrismLibrary.sln
  - dotnet restore PrismLibrary.sln  

build:
  parallel: true
  project: PrismLibrary.sln

test_script:
  - dotnet test test\Prism.Tests\Prism.Tests.csproj
  - vstest.console /logger:Appveyor test\Prism.Wpf.Tests\bin\Debug\Prism.Wpf.Tests.dll
  - vstest.console /logger:Appveyor test\Prism.Autofac.Wpf.Tests\bin\Debug\Prism.Autofac.Wpf.Tests.dll
  - vstest.console /logger:Appveyor test\Prism.DryIoc.Wpf.Tests\bin\Debug\Prism.DryIoc.Wpf.Tests.dll
  - vstest.console /logger:Appveyor test\Prism.Mef.Wpf.Tests\bin\Debug\Prism.Mef.Wpf.Tests.dll
  - vstest.console /logger:Appveyor test\Prism.StructureMap.Wpf.Tests\bin\Debug\Prism.StructureMap.Wpf.Tests.dll
  - vstest.console /logger:Appveyor test\Prism.Unity.Wpf.Tests\bin\Debug\Prism.Unity.Wpf.Tests.dll
  # Xamarin tests are currently disabled due to a blocking issue: https://bugzilla.xamarin.com/show_bug.cgi?id=53060
  # UWP tests are not currently not supported by appveyor: https://github.com/appveyor/ci/issues/393

after_test:
  - dotnet pack src\Prism\ -c Release
  # Xamarin packaging is currently disabled due to a blocking issue: https://bugzilla.xamarin.com/show_bug.cgi?id=53060
  - ps nuspecs\CreateWpfWindowsNugetPackages.ps1

artifacts:
  path: 'src\**\*.nupkg'
  name: Nuget

deploy:  
- provider: NuGet
  name: nuget_prerelease
  server: https://www.myget.org/F/Prism/api/v2/package
  api_key:
    secure: asd
  skip_symbols: true
  on:
    branch: master