<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UseMaui>true</UseMaui>
    <IsPackable>false</IsPackable>
    <MauiXamlInflator>SourceGen</MauiXamlInflator>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <WarningsAsErrors>$(WarningsAsErrors);XC0103</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" VersionOverride="10.0.10" />
    <PackageReference Include="xunit" />
    <ProjectReference Include="../../../src/Maui/Prism.Maui/Prism.Maui.csproj" />
  </ItemGroup>
</Project>
