<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Xunit.StaFact" />
    <Compile Include="../../../tests/Prism.DefaultView.Shared/DefaultViewLifecycleFixture.cs" />
    <ProjectReference Include="../../../src/Wpf/Prism.Wpf/Prism.Wpf.csproj" />
  </ItemGroup>
</Project>
