// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved


// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.BindableValidator.#EmptyErrorsCollection", Justification = "ReadOnlyCollection<string> is immutable.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.ViewModelLocator.#AutoWireViewModelProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.Prism.StoreApps.Flyouts.IFlyoutViewModel", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.Flyouts.IFlyoutViewModel.#CloseFlyout", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "0#", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.BindableBase.#SetProperty`1(!!0&,!!0,System.String)", Justification = "Template provided BindableBase requires pass by reference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.BindableBase.#SetProperty`1(!!0&,!!0,System.String)", Justification = "CallerMemberNameAttribute requires a default parameter.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.Interfaces.IFrameFacade.#GetNavigationState()", Justification = "Matching Frame api.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Validatable", Scope = "type", Target = "Microsoft.Practices.Prism.StoreApps.Interfaces.IValidatableBindableBase", Justification = "Validatable is a technical term that represents something that can be validated.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mvvm", Scope = "type", Target = "Microsoft.Practices.Prism.StoreApps.MvvmAppBase", Justification = "Mvvm is a standard term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mvvm", Scope = "type", Target = "Microsoft.Practices.Prism.StoreApps.MvvmNavigatedEventArgs", Justification = "Mvvm is a standard term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Validatable", Scope = "type", Target = "Microsoft.Practices.Prism.StoreApps.ValidatableBindableBase", Justification = "Validatable is a technical term that represents something that can be validated.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.ValidatableBindableBase.#SetProperty`1(!!0&,!!0,System.String)", Justification = "CallerMemberNameAttribute requires a default parameter.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.VisualStateAwarePage.#GetSessionStateForFrame", Justification = "Nesting is required by Func<T1, T2>.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.Prism.StoreApps.Interfaces.IFlyoutViewModel", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.Interfaces.IFlyoutViewModel.#CloseFlyout", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.DelegateCommand`1.#FromAsyncHandler(System.Func`2<!0,System.Threading.Tasks.Task>)", Justification = "Factory method required for type inference.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.DelegateCommand`1.#FromAsyncHandler(System.Func`2<!0,System.Threading.Tasks.Task>,System.Func`2<!0,System.Boolean>)", Justification = "Factory method required for type inference.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.BindableValidator.#Errors", Justification = "This class exposes the Errors IDictionary so that it can be indexed by XAML using a field name as key.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.BindableValidator.#GetAllErrors()", Justification = "This method can return a different collection of errors on subsequent calls.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.BindableValidator.#GetAllErrors()", Justification = "This class exposes the Errors IDictionary so that it can be indexed by XAML using a field name as key.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.BindableValidator.#SetAllErrors(System.Collections.Generic.IDictionary`2<System.String,System.Collections.ObjectModel.ReadOnlyCollection`1<System.String>>)", Justification = "This Set method populates the BindableValidator with data.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.Interfaces.IValidatableBindableBase.#GetAllErrors()", Justification = "This method can return a different collection of errors on subsequent calls.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.Interfaces.IValidatableBindableBase.#GetAllErrors()", Justification = "This method returns errors in the form of a name value pair where the name refers to a field name and the value refers to the related errors.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.Interfaces.IValidatableBindableBase.#SetAllErrors(System.Collections.Generic.IDictionary`2<System.String,System.Collections.ObjectModel.ReadOnlyCollection`1<System.String>>)", Justification = "The SetAllErrors method populates object instances with the underlying error dictionary.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.AppManifestHelper.#GetApplicationId()", Justification = "This method walks through the app manifest to find the ApplicationId. This is a time intensive operation.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "eventArgs", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.VisualStateAwarePage.#StartLayoutUpdates(System.Object,Windows.UI.Xaml.RoutedEventArgs)", Justification = "Cannot removed parameter because this method is an event handler.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "eventArgs", Scope = "member", Target = "Microsoft.Practices.Prism.StoreApps.VisualStateAwarePage.#StopLayoutUpdates(System.Object,Windows.UI.Xaml.RoutedEventArgs)", Justification = "Cannot removed parameter because this method is an event handler.")]
