//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prism.Mef.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prism.Mef.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper sequence completed.
        /// </summary>
        internal static string BootstrapperSequenceCompleted {
            get {
                return ResourceManager.GetString("BootstrapperSequenceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring catalog for MEF.
        /// </summary>
        internal static string ConfiguringCatalogForMEF {
            get {
                return ResourceManager.GetString("ConfiguringCatalogForMEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring default region behaviors.
        /// </summary>
        internal static string ConfiguringDefaultRegionBehaviors {
            get {
                return ResourceManager.GetString("ConfiguringDefaultRegionBehaviors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring MEF container.
        /// </summary>
        internal static string ConfiguringMefContainer {
            get {
                return ResourceManager.GetString("ConfiguringMefContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring module catalog..
        /// </summary>
        internal static string ConfiguringModuleCatalog {
            get {
                return ResourceManager.GetString("ConfiguringModuleCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring region adapters.
        /// </summary>
        internal static string ConfiguringRegionAdapters {
            get {
                return ResourceManager.GetString("ConfiguringRegionAdapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring ServiceLocator singleton.
        /// </summary>
        internal static string ConfiguringServiceLocatorSingleton {
            get {
                return ResourceManager.GetString("ConfiguringServiceLocatorSingleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring the ViewModelLocator to use MEF.
        /// </summary>
        internal static string ConfiguringViewModelLocator {
            get {
                return ResourceManager.GetString("ConfiguringViewModelLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating catalog for MEF.
        /// </summary>
        internal static string CreatingCatalogForMEF {
            get {
                return ResourceManager.GetString("CreatingCatalogForMEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Mef container.
        /// </summary>
        internal static string CreatingMefContainer {
            get {
                return ResourceManager.GetString("CreatingMefContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating module catalog..
        /// </summary>
        internal static string CreatingModuleCatalog {
            get {
                return ResourceManager.GetString("CreatingModuleCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating shell.
        /// </summary>
        internal static string CreatingShell {
            get {
                return ResourceManager.GetString("CreatingShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the module with type &apos;{0}&apos; among the exported modules. Make sure the module name in the module catalog matches that specified on ModuleExportAttribute for the module type..
        /// </summary>
        internal static string FailedToGetType {
            get {
                return ResourceManager.GetString("FailedToGetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing modules.
        /// </summary>
        internal static string InitializingModules {
            get {
                return ResourceManager.GetString("InitializingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing shell.
        /// </summary>
        internal static string InitializingShell {
            get {
                return ResourceManager.GetString("InitializingShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger was created successfully..
        /// </summary>
        internal static string LoggerWasCreatedSuccessfully {
            get {
                return ResourceManager.GetString("LoggerWasCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CompositionContainer is required and cannot be null..
        /// </summary>
        internal static string NullCompositionContainerException {
            get {
                return ResourceManager.GetString("NullCompositionContainerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ILoggerFacade is required and cannot be null..
        /// </summary>
        internal static string NullLoggerFacadeException {
            get {
                return ResourceManager.GetString("NullLoggerFacadeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IModuleCatalog is required and cannot be null in order to initialize the modules..
        /// </summary>
        internal static string NullModuleCatalogException {
            get {
                return ResourceManager.GetString("NullModuleCatalogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Framework Exception Types.
        /// </summary>
        internal static string RegisteringFrameworkExceptionTypes {
            get {
                return ResourceManager.GetString("RegisteringFrameworkExceptionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the RegionManager..
        /// </summary>
        internal static string SettingTheRegionManager {
            get {
                return ResourceManager.GetString("SettingTheRegionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Regions..
        /// </summary>
        internal static string UpdatingRegions {
            get {
                return ResourceManager.GetString("UpdatingRegions", resourceCulture);
            }
        }
    }
}
