name: build_wpf

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build_wpf.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - xunit.runner.json
      - 'src/Prism.Core/**'
      - 'src/Prism.Events/**'
      - 'tests/Prism.Core.Tests/**'
      - 'src/Wpf/**'
      - 'tests/Wpf/**'

jobs:
  build-prism-wpf:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@8fa02d57679e5db1fc83aebdac99fd494c4e510e # v2 with private feed URL secret support
    with:
      name: Build Prism.Wpf
      solution-path: PrismLibrary_Wpf.slnf
      test-projects: |
        tests/Wpf/Prism.Wpf.Tests/Prism.Wpf.Tests.csproj
        tests/Wpf/Prism.DryIoc.Wpf.Tests/Prism.DryIoc.Wpf.Tests.csproj
        tests/Wpf/Prism.Unity.Wpf.Tests/Prism.Unity.Wpf.Tests.csproj
      dotnet-version: 10.0.100
    secrets:
      nugetFeedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      nugetUserName: ${{ secrets.IN_HOUSE_USER }}
      nugetToken: ${{ secrets.IN_HOUSE_API_KEY }}
