name: build_uno

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build_uno.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - xunit.runner.json
      - 'src/Prism.Core/**'
      - 'src/Prism.Events/**'
      - 'tests/Prism.Core.Tests/**'
      - 'src/Wpf/**'
      - 'tests/Wpf/**'
      - 'src/Uno/**'
      - 'tests/Uno/**'

jobs:
  build-prism-uno:
    uses: avantipoint/workflow-templates/.github/workflows/msbuild-build.yml@8fa02d57679e5db1fc83aebdac99fd494c4e510e # v2 with private feed URL secret support
    with:
      name: Build Prism.Uno
      solution-path: PrismLibrary_Uno.slnf
      windows-sdk-version: 18362
      dotnet-version: 10.0.100
      install-workload: ios android macos maccatalyst wasm-tools tvos
      uno-check: false
      uno-check-version: 1.33.1
      uno-check-parameters: '--skip xcode --skip gtk3 --skip vswin --skip androidemulator --skip androidsdk --skip vsmac --skip dotnetnewunotemplates'
      test-projects: |
        tests/Uno/Prism.Uno.WinUI.Tests/Prism.Uno.WinUI.Tests.csproj
        tests/Uno/Prism.DryIoc.Uno.WinUI.Tests/Prism.DryIoc.Uno.WinUI.Tests.csproj
    secrets:
      nugetFeedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      nugetUserName: ${{ secrets.IN_HOUSE_USER }}
      nugetToken: ${{ secrets.IN_HOUSE_API_KEY }}
