name: build_core

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build_core.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - xunit.runner.json
      - 'src/Prism.Core/**'
      - 'src/Prism.Events/**'
      - 'tests/Prism.Core.Tests/**'

jobs:
  build-prism-core:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@61adf86e5d3b2836b2b76fdb67cb71076521a9d7 # v2 with private feed URL secret support
    with:
      name: Build Prism.Core
      solution-path: PrismLibrary_Core.slnf
      test-projects: |
        tests/Prism.Core.Tests/Prism.Core.Tests.csproj
      dotnet-version: 10.0.100
    secrets:
      nugetFeedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      nugetUserName: ${{ secrets.IN_HOUSE_USER }}
      nugetToken: ${{ secrets.IN_HOUSE_API_KEY }}
