name: build_maui

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build_maui.yml
      - global.json
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - xunit.runner.json
      - 'src/Prism.Core/**'
      - 'src/Prism.Events/**'
      - 'tests/Prism.Core.Tests/**'
      - 'src/Maui/**'
      - 'tests/Containers/**'
      - 'tests/Maui/**'
      - 'e2e/Maui/**'

jobs:
  build-prism-maui:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@61adf86e5d3b2836b2b76fdb67cb71076521a9d7 # v2 with private feed URL secret support
    with:
      name: Build Prism.Maui
      solution-path: PrismLibrary_Maui.slnf
      install-workload: maui maui-tizen --version 11.0.100-rc.1.26458.5
      test-projects: |
        tests/Maui/Prism.Maui.Tests/Prism.Maui.Tests.csproj
        tests/Maui/Prism.DryIoc.Maui.Tests/Prism.DryIoc.Maui.Tests.csproj
      dotnet-version: |
        10.0.100
        11.0.100-rc.1.26425.128
    secrets:
      nugetFeedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      nugetUserName: ${{ secrets.IN_HOUSE_USER }}
      nugetToken: ${{ secrets.IN_HOUSE_API_KEY }}
