<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <UseMaui>true</UseMaui>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.10" Condition="$(TargetFramework.StartsWith('net10'))" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="11.0.0-rc.1.26451.6" Condition="$(TargetFramework.StartsWith('net11'))" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Maui\Prism.Maui\Prism.Maui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Remove="**\*.xaml" />
    <MauiXaml Include="**\*.xaml" Exclude="$(DefaultItemExcludes)" />
  </ItemGroup>
</Project>
